version: '3'

services:
  web:
    build: .
    env_file: 
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/AbhrilSoft_app
    depends_on:
      - db
  db:
    image: postgres:14.7
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: